<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>C# + Revit API: Case Study №1 [Section Automation] | Blog</title><meta name=keywords content="C#,Revit,Tutorial"><meta name=description content="Introduction
![[Pasted image 20250829161635.png]]
Project Solution


 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


Solution
|-> ViewOnSheets2025
	|-> Dependencies
	|-> Properties
	|-> Commands
		|-> Cmd_AutoSect.cs
		|-> AutoSection
			|-> Cmd_AutoSectByBody.cs
			|-> Cmd_AutoSectByModel.cs
			|-> Cmd_AutoSectByPlane.cs
		|-> General
	|-> Extensions
		|-> AutoSection
			|-> Element_AutoSectionExt.cs
			|-> ViewSection_AutoSectionExt.cs
		|-> Document_Ext.cs
		|-> Element_Ext.cs
		|-> PulldownButton_Ext.cs
		|-> RibbonPanel_Ext.cs
		|-> UIControlledApplication_Ext.cs
		|-> ViewSection_Ext.cs
	|-> General 
		|-> Globals.cs
	|-> Models
		|-> AutoSection
			|-> BodySection
				|-> ElementTypeInfo.cs
				|-> SectionCreationSettings.cs
			|-> Common
				|-> AutoSectScenario.cs
			|-> ReferencePlaneItem.cs
	|-> Resources
		|-> Icons
	|-> Services
		|-> AutoSection
			|-> BodySectionService.cs
			|-> ModelSectionService.cs
			|-> PlaneSectionService.cs
		|-> SectionCreationService.cs
	|-> Utilities
		|-> Geometry_Utils.cs
		|-> Ribbon_Utils.cs
	|-> Views
		|-> AutoSectScenarioWindow.xaml
		|-> ReferencePlaneSelectionWindow.xaml
		|-> RevitSectionCreatorWindow.xaml
	|-> Application.cs  
	|-> Host.cs         
	|-> UKON.addin



Cmd_AutoSect.cs


 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41


using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using UKON.Views;
using UKON.Models.AutoSection.Common;
using UKON.Commands.AutoSection;
using System;

namespace UKON.Commands
{
    [Transaction(TransactionMode.Manual)]
    public class Cmd_AutoSect : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            try
            {
                // Показать диалог выбора типа разреза
                var scenarioWindow = new AutoSectScenarioWindow();
                if (scenarioWindow.ShowDialog() != true)
                    return Result.Cancelled;

                var selectedScenario = scenarioWindow.SelectedScenario;
                
                // Делегировать выполнение соответствующей команде
                return selectedScenario switch
                {
                    AutoSectScenario.ByBody => new Cmd_AutoSectByBody().Execute(commandData, ref message, elements),
                    AutoSectScenario.ByPlane => new Cmd_AutoSectByPlane().Execute(commandData, ref message, elements),
                    AutoSectScenario.ByModel => new Cmd_AutoSectByModel().Execute(commandData, ref message, elements),
                    _ => Result.Cancelled
                };
            }
            catch (Exception ex)
            {
                message = ex.Message;
                return Result.Failed;
            }
        }
    }
}


Cmd_AutoSectByPlane.cs


 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31


using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using UKON.Services;
using UKON.Services.AutoSection;
using System;

namespace UKON.Commands.AutoSection
{
    [Transaction(TransactionMode.Manual)]
    public class Cmd_AutoSectByPlane : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            var uiApp = commandData.Application;
            var uiDoc = uiApp.ActiveUIDocument;
            var doc = uiDoc.Document;

            try
            {
                var planeSectionService = Host.GetService<PlaneSectionService>();
                return planeSectionService.ExecuteByPlane(uiDoc);
            }
            catch (Exception ex)
            {
                message = ex.Message;
                return Result.Failed;
            }
        }
    }
}


"><meta name=author content><link rel=canonical href=https://blog.aydrafting.com/posts/case-1/><link crossorigin=anonymous href=/assets/css/stylesheet.6d585472a409a8f504e6bf969a2864fd1288e629997cd2926dd96376ae22831b.css integrity="sha256-bVhUcqQJqPUE5r+Wmihk/RKI5imZfNKSbdljdq4igxs=" rel="preload stylesheet" as=style><link rel=icon href=https://blog.aydrafting.com/favicon.ico><link rel=icon type=image/png sizes=16x16 href=https://blog.aydrafting.com/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=https://blog.aydrafting.com/favicon-32x32.png><link rel=apple-touch-icon href=https://blog.aydrafting.com/apple-touch-icon.png><link rel=mask-icon href=https://blog.aydrafting.com/safari-pinned-tab.svg><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><link rel=alternate hreflang=en href=https://blog.aydrafting.com/posts/case-1/><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--code-block-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><meta property="og:url" content="https://blog.aydrafting.com/posts/case-1/"><meta property="og:site_name" content="Blog"><meta property="og:title" content="C# + Revit API: Case Study №1 [Section Automation]"><meta property="og:description" content="Introduction ![[Pasted image 20250829161635.png]]
Project Solution 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 Solution |-> ViewOnSheets2025 |-> Dependencies |-> Properties |-> Commands |-> Cmd_AutoSect.cs |-> AutoSection |-> Cmd_AutoSectByBody.cs |-> Cmd_AutoSectByModel.cs |-> Cmd_AutoSectByPlane.cs |-> General |-> Extensions |-> AutoSection |-> Element_AutoSectionExt.cs |-> ViewSection_AutoSectionExt.cs |-> Document_Ext.cs |-> Element_Ext.cs |-> PulldownButton_Ext.cs |-> RibbonPanel_Ext.cs |-> UIControlledApplication_Ext.cs |-> ViewSection_Ext.cs |-> General |-> Globals.cs |-> Models |-> AutoSection |-> BodySection |-> ElementTypeInfo.cs |-> SectionCreationSettings.cs |-> Common |-> AutoSectScenario.cs |-> ReferencePlaneItem.cs |-> Resources |-> Icons |-> Services |-> AutoSection |-> BodySectionService.cs |-> ModelSectionService.cs |-> PlaneSectionService.cs |-> SectionCreationService.cs |-> Utilities |-> Geometry_Utils.cs |-> Ribbon_Utils.cs |-> Views |-> AutoSectScenarioWindow.xaml |-> ReferencePlaneSelectionWindow.xaml |-> RevitSectionCreatorWindow.xaml |-> Application.cs |-> Host.cs |-> UKON.addin Cmd_AutoSect.cs 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 using Autodesk.Revit.Attributes; using Autodesk.Revit.DB; using Autodesk.Revit.UI; using UKON.Views; using UKON.Models.AutoSection.Common; using UKON.Commands.AutoSection; using System; namespace UKON.Commands { [Transaction(TransactionMode.Manual)] public class Cmd_AutoSect : IExternalCommand { public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements) { try { // Показать диалог выбора типа разреза var scenarioWindow = new AutoSectScenarioWindow(); if (scenarioWindow.ShowDialog() != true) return Result.Cancelled; var selectedScenario = scenarioWindow.SelectedScenario; // Делегировать выполнение соответствующей команде return selectedScenario switch { AutoSectScenario.ByBody => new Cmd_AutoSectByBody().Execute(commandData, ref message, elements), AutoSectScenario.ByPlane => new Cmd_AutoSectByPlane().Execute(commandData, ref message, elements), AutoSectScenario.ByModel => new Cmd_AutoSectByModel().Execute(commandData, ref message, elements), _ => Result.Cancelled }; } catch (Exception ex) { message = ex.Message; return Result.Failed; } } } } Cmd_AutoSectByPlane.cs 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 using Autodesk.Revit.Attributes; using Autodesk.Revit.DB; using Autodesk.Revit.UI; using UKON.Services; using UKON.Services.AutoSection; using System; namespace UKON.Commands.AutoSection { [Transaction(TransactionMode.Manual)] public class Cmd_AutoSectByPlane : IExternalCommand { public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements) { var uiApp = commandData.Application; var uiDoc = uiApp.ActiveUIDocument; var doc = uiDoc.Document; try { var planeSectionService = Host.GetService<PlaneSectionService>(); return planeSectionService.ExecuteByPlane(uiDoc); } catch (Exception ex) { message = ex.Message; return Result.Failed; } } } } "><meta property="og:locale" content="en-us"><meta property="og:type" content="article"><meta property="article:section" content="posts"><meta property="article:published_time" content="2025-01-03T19:10:51+03:00"><meta property="article:modified_time" content="2025-01-03T19:10:51+03:00"><meta property="article:tag" content="C#"><meta property="article:tag" content="Revit"><meta property="article:tag" content="Tutorial"><meta name=twitter:card content="summary"><meta name=twitter:title content="C# + Revit API: Case Study №1 [Section Automation]"><meta name=twitter:description content="Introduction
![[Pasted image 20250829161635.png]]
Project Solution


 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


Solution
|-> ViewOnSheets2025
	|-> Dependencies
	|-> Properties
	|-> Commands
		|-> Cmd_AutoSect.cs
		|-> AutoSection
			|-> Cmd_AutoSectByBody.cs
			|-> Cmd_AutoSectByModel.cs
			|-> Cmd_AutoSectByPlane.cs
		|-> General
	|-> Extensions
		|-> AutoSection
			|-> Element_AutoSectionExt.cs
			|-> ViewSection_AutoSectionExt.cs
		|-> Document_Ext.cs
		|-> Element_Ext.cs
		|-> PulldownButton_Ext.cs
		|-> RibbonPanel_Ext.cs
		|-> UIControlledApplication_Ext.cs
		|-> ViewSection_Ext.cs
	|-> General 
		|-> Globals.cs
	|-> Models
		|-> AutoSection
			|-> BodySection
				|-> ElementTypeInfo.cs
				|-> SectionCreationSettings.cs
			|-> Common
				|-> AutoSectScenario.cs
			|-> ReferencePlaneItem.cs
	|-> Resources
		|-> Icons
	|-> Services
		|-> AutoSection
			|-> BodySectionService.cs
			|-> ModelSectionService.cs
			|-> PlaneSectionService.cs
		|-> SectionCreationService.cs
	|-> Utilities
		|-> Geometry_Utils.cs
		|-> Ribbon_Utils.cs
	|-> Views
		|-> AutoSectScenarioWindow.xaml
		|-> ReferencePlaneSelectionWindow.xaml
		|-> RevitSectionCreatorWindow.xaml
	|-> Application.cs  
	|-> Host.cs         
	|-> UKON.addin



Cmd_AutoSect.cs


 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41


using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using UKON.Views;
using UKON.Models.AutoSection.Common;
using UKON.Commands.AutoSection;
using System;

namespace UKON.Commands
{
    [Transaction(TransactionMode.Manual)]
    public class Cmd_AutoSect : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            try
            {
                // Показать диалог выбора типа разреза
                var scenarioWindow = new AutoSectScenarioWindow();
                if (scenarioWindow.ShowDialog() != true)
                    return Result.Cancelled;

                var selectedScenario = scenarioWindow.SelectedScenario;
                
                // Делегировать выполнение соответствующей команде
                return selectedScenario switch
                {
                    AutoSectScenario.ByBody => new Cmd_AutoSectByBody().Execute(commandData, ref message, elements),
                    AutoSectScenario.ByPlane => new Cmd_AutoSectByPlane().Execute(commandData, ref message, elements),
                    AutoSectScenario.ByModel => new Cmd_AutoSectByModel().Execute(commandData, ref message, elements),
                    _ => Result.Cancelled
                };
            }
            catch (Exception ex)
            {
                message = ex.Message;
                return Result.Failed;
            }
        }
    }
}


Cmd_AutoSectByPlane.cs


 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31


using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using UKON.Services;
using UKON.Services.AutoSection;
using System;

namespace UKON.Commands.AutoSection
{
    [Transaction(TransactionMode.Manual)]
    public class Cmd_AutoSectByPlane : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            var uiApp = commandData.Application;
            var uiDoc = uiApp.ActiveUIDocument;
            var doc = uiDoc.Document;

            try
            {
                var planeSectionService = Host.GetService<PlaneSectionService>();
                return planeSectionService.ExecuteByPlane(uiDoc);
            }
            catch (Exception ex)
            {
                message = ex.Message;
                return Result.Failed;
            }
        }
    }
}


"><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Posts","item":"https://blog.aydrafting.com/posts/"},{"@type":"ListItem","position":2,"name":"C# + Revit API: Case Study №1 [Section Automation]","item":"https://blog.aydrafting.com/posts/case-1/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"C# + Revit API: Case Study №1 [Section Automation]","name":"C# \u002b Revit API: Case Study №1 [Section Automation]","description":"Introduction ![[Pasted image 20250829161635.png]]\nProject Solution 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 Solution |-\u0026gt; ViewOnSheets2025 |-\u0026gt; Dependencies |-\u0026gt; Properties |-\u0026gt; Commands |-\u0026gt; Cmd_AutoSect.cs |-\u0026gt; AutoSection |-\u0026gt; Cmd_AutoSectByBody.cs |-\u0026gt; Cmd_AutoSectByModel.cs |-\u0026gt; Cmd_AutoSectByPlane.cs |-\u0026gt; General |-\u0026gt; Extensions |-\u0026gt; AutoSection |-\u0026gt; Element_AutoSectionExt.cs |-\u0026gt; ViewSection_AutoSectionExt.cs |-\u0026gt; Document_Ext.cs |-\u0026gt; Element_Ext.cs |-\u0026gt; PulldownButton_Ext.cs |-\u0026gt; RibbonPanel_Ext.cs |-\u0026gt; UIControlledApplication_Ext.cs |-\u0026gt; ViewSection_Ext.cs |-\u0026gt; General |-\u0026gt; Globals.cs |-\u0026gt; Models |-\u0026gt; AutoSection |-\u0026gt; BodySection |-\u0026gt; ElementTypeInfo.cs |-\u0026gt; SectionCreationSettings.cs |-\u0026gt; Common |-\u0026gt; AutoSectScenario.cs |-\u0026gt; ReferencePlaneItem.cs |-\u0026gt; Resources |-\u0026gt; Icons |-\u0026gt; Services |-\u0026gt; AutoSection |-\u0026gt; BodySectionService.cs |-\u0026gt; ModelSectionService.cs |-\u0026gt; PlaneSectionService.cs |-\u0026gt; SectionCreationService.cs |-\u0026gt; Utilities |-\u0026gt; Geometry_Utils.cs |-\u0026gt; Ribbon_Utils.cs |-\u0026gt; Views |-\u0026gt; AutoSectScenarioWindow.xaml |-\u0026gt; ReferencePlaneSelectionWindow.xaml |-\u0026gt; RevitSectionCreatorWindow.xaml |-\u0026gt; Application.cs |-\u0026gt; Host.cs |-\u0026gt; UKON.addin Cmd_AutoSect.cs 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 using Autodesk.Revit.Attributes; using Autodesk.Revit.DB; using Autodesk.Revit.UI; using UKON.Views; using UKON.Models.AutoSection.Common; using UKON.Commands.AutoSection; using System; namespace UKON.Commands { [Transaction(TransactionMode.Manual)] public class Cmd_AutoSect : IExternalCommand { public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements) { try { // Показать диалог выбора типа разреза var scenarioWindow = new AutoSectScenarioWindow(); if (scenarioWindow.ShowDialog() != true) return Result.Cancelled; var selectedScenario = scenarioWindow.SelectedScenario; // Делегировать выполнение соответствующей команде return selectedScenario switch { AutoSectScenario.ByBody =\u0026gt; new Cmd_AutoSectByBody().Execute(commandData, ref message, elements), AutoSectScenario.ByPlane =\u0026gt; new Cmd_AutoSectByPlane().Execute(commandData, ref message, elements), AutoSectScenario.ByModel =\u0026gt; new Cmd_AutoSectByModel().Execute(commandData, ref message, elements), _ =\u0026gt; Result.Cancelled }; } catch (Exception ex) { message = ex.Message; return Result.Failed; } } } } Cmd_AutoSectByPlane.cs 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 using Autodesk.Revit.Attributes; using Autodesk.Revit.DB; using Autodesk.Revit.UI; using UKON.Services; using UKON.Services.AutoSection; using System; namespace UKON.Commands.AutoSection { [Transaction(TransactionMode.Manual)] public class Cmd_AutoSectByPlane : IExternalCommand { public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements) { var uiApp = commandData.Application; var uiDoc = uiApp.ActiveUIDocument; var doc = uiDoc.Document; try { var planeSectionService = Host.GetService\u0026lt;PlaneSectionService\u0026gt;(); return planeSectionService.ExecuteByPlane(uiDoc); } catch (Exception ex) { message = ex.Message; return Result.Failed; } } } } ","keywords":["C#","Revit","Tutorial"],"articleBody":"Introduction ![[Pasted image 20250829161635.png]]\nProject Solution 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 Solution |-\u003e ViewOnSheets2025 |-\u003e Dependencies |-\u003e Properties |-\u003e Commands |-\u003e Cmd_AutoSect.cs |-\u003e AutoSection |-\u003e Cmd_AutoSectByBody.cs |-\u003e Cmd_AutoSectByModel.cs |-\u003e Cmd_AutoSectByPlane.cs |-\u003e General |-\u003e Extensions |-\u003e AutoSection |-\u003e Element_AutoSectionExt.cs |-\u003e ViewSection_AutoSectionExt.cs |-\u003e Document_Ext.cs |-\u003e Element_Ext.cs |-\u003e PulldownButton_Ext.cs |-\u003e RibbonPanel_Ext.cs |-\u003e UIControlledApplication_Ext.cs |-\u003e ViewSection_Ext.cs |-\u003e General |-\u003e Globals.cs |-\u003e Models |-\u003e AutoSection |-\u003e BodySection |-\u003e ElementTypeInfo.cs |-\u003e SectionCreationSettings.cs |-\u003e Common |-\u003e AutoSectScenario.cs |-\u003e ReferencePlaneItem.cs |-\u003e Resources |-\u003e Icons |-\u003e Services |-\u003e AutoSection |-\u003e BodySectionService.cs |-\u003e ModelSectionService.cs |-\u003e PlaneSectionService.cs |-\u003e SectionCreationService.cs |-\u003e Utilities |-\u003e Geometry_Utils.cs |-\u003e Ribbon_Utils.cs |-\u003e Views |-\u003e AutoSectScenarioWindow.xaml |-\u003e ReferencePlaneSelectionWindow.xaml |-\u003e RevitSectionCreatorWindow.xaml |-\u003e Application.cs |-\u003e Host.cs |-\u003e UKON.addin Cmd_AutoSect.cs 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 using Autodesk.Revit.Attributes; using Autodesk.Revit.DB; using Autodesk.Revit.UI; using UKON.Views; using UKON.Models.AutoSection.Common; using UKON.Commands.AutoSection; using System; namespace UKON.Commands { [Transaction(TransactionMode.Manual)] public class Cmd_AutoSect : IExternalCommand { public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements) { try { // Показать диалог выбора типа разреза var scenarioWindow = new AutoSectScenarioWindow(); if (scenarioWindow.ShowDialog() != true) return Result.Cancelled; var selectedScenario = scenarioWindow.SelectedScenario; // Делегировать выполнение соответствующей команде return selectedScenario switch { AutoSectScenario.ByBody =\u003e new Cmd_AutoSectByBody().Execute(commandData, ref message, elements), AutoSectScenario.ByPlane =\u003e new Cmd_AutoSectByPlane().Execute(commandData, ref message, elements), AutoSectScenario.ByModel =\u003e new Cmd_AutoSectByModel().Execute(commandData, ref message, elements), _ =\u003e Result.Cancelled }; } catch (Exception ex) { message = ex.Message; return Result.Failed; } } } } Cmd_AutoSectByPlane.cs 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 using Autodesk.Revit.Attributes; using Autodesk.Revit.DB; using Autodesk.Revit.UI; using UKON.Services; using UKON.Services.AutoSection; using System; namespace UKON.Commands.AutoSection { [Transaction(TransactionMode.Manual)] public class Cmd_AutoSectByPlane : IExternalCommand { public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements) { var uiApp = commandData.Application; var uiDoc = uiApp.ActiveUIDocument; var doc = uiDoc.Document; try { var planeSectionService = Host.GetService\u003cPlaneSectionService\u003e(); return planeSectionService.ExecuteByPlane(uiDoc); } catch (Exception ex) { message = ex.Message; return Result.Failed; } } } } ","wordCount":"397","inLanguage":"en","datePublished":"2025-01-03T19:10:51+03:00","dateModified":"2025-01-03T19:10:51+03:00","mainEntityOfPage":{"@type":"WebPage","@id":"https://blog.aydrafting.com/posts/case-1/"},"publisher":{"@type":"Organization","name":"Blog","logo":{"@type":"ImageObject","url":"https://blog.aydrafting.com/favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://blog.aydrafting.com/ accesskey=h title="Blog (Alt + H)">Blog</a></div><div class="logo main-logo"><a href=https://aydrafting.com target=_blank><img src=/LogoAYD.png alt=Blog height=40></a></div><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)">
<svg id="moon" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg>
<svg id="sun" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=https://blog.aydrafting.com/>Home</a>&nbsp;»&nbsp;<a href=https://blog.aydrafting.com/posts/>Posts</a></div><h1 class="post-title entry-hint-parent">C# + Revit API: Case Study №1 [Section Automation]</h1><div class=post-meta><span title='2025-01-03 19:10:51 +0300 MSK'>January 3, 2025</span>&nbsp;·&nbsp;2 min&nbsp;|&nbsp;<a href=mailto:%20aydimir@aydrafting.com rel="noopener noreferrer edit" target=_blank>Suggest Changes</a></div></header><div class=toc><details><summary accesskey=c title="(Alt + C)"><span class=details>Table of Contents</span></summary><div class=inner><ul><li><a href=#introduction aria-label=Introduction>Introduction</a><ul><li><a href=#project-solution aria-label="Project Solution">Project Solution</a></li></ul></li><li><a href=#cmd_autosectcs aria-label=Cmd_AutoSect.cs>Cmd_AutoSect.cs</a></li><li><a href=#cmd_autosectbyplanecs aria-label=Cmd_AutoSectByPlane.cs>Cmd_AutoSectByPlane.cs</a></li></ul></div></details></div><div class=post-content><h1 id=introduction>Introduction<a hidden class=anchor aria-hidden=true href=#introduction>#</a></h1><p>![[Pasted image 20250829161635.png]]</p><h2 id=project-solution><code>Project Solution</code><a hidden class=anchor aria-hidden=true href=#project-solution>#</a></h2><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span><span class=lnt>11
</span><span class=lnt>12
</span><span class=lnt>13
</span><span class=lnt>14
</span><span class=lnt>15
</span><span class=lnt>16
</span><span class=lnt>17
</span><span class=lnt>18
</span><span class=lnt>19
</span><span class=lnt>20
</span><span class=lnt>21
</span><span class=lnt>22
</span><span class=lnt>23
</span><span class=lnt>24
</span><span class=lnt>25
</span><span class=lnt>26
</span><span class=lnt>27
</span><span class=lnt>28
</span><span class=lnt>29
</span><span class=lnt>30
</span><span class=lnt>31
</span><span class=lnt>32
</span><span class=lnt>33
</span><span class=lnt>34
</span><span class=lnt>35
</span><span class=lnt>36
</span><span class=lnt>37
</span><span class=lnt>38
</span><span class=lnt>39
</span><span class=lnt>40
</span><span class=lnt>41
</span><span class=lnt>42
</span><span class=lnt>43
</span><span class=lnt>44
</span><span class=lnt>45
</span><span class=lnt>46
</span><span class=lnt>47
</span><span class=lnt>48
</span><span class=lnt>49
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-bash data-lang=bash><span class=line><span class=cl>Solution
</span></span><span class=line><span class=cl><span class=p>|</span>-&gt; ViewOnSheets2025
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Dependencies
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Properties
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Commands
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; Cmd_AutoSect.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; AutoSection
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; Cmd_AutoSectByBody.cs
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; Cmd_AutoSectByModel.cs
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; Cmd_AutoSectByPlane.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; General
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Extensions
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; AutoSection
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; Element_AutoSectionExt.cs
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; ViewSection_AutoSectionExt.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; Document_Ext.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; Element_Ext.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; PulldownButton_Ext.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; RibbonPanel_Ext.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; UIControlledApplication_Ext.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; ViewSection_Ext.cs
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; General 
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; Globals.cs
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Models
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; AutoSection
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; BodySection
</span></span><span class=line><span class=cl>				<span class=p>|</span>-&gt; ElementTypeInfo.cs
</span></span><span class=line><span class=cl>				<span class=p>|</span>-&gt; SectionCreationSettings.cs
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; Common
</span></span><span class=line><span class=cl>				<span class=p>|</span>-&gt; AutoSectScenario.cs
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; ReferencePlaneItem.cs
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Resources
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; Icons
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Services
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; AutoSection
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; BodySectionService.cs
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; ModelSectionService.cs
</span></span><span class=line><span class=cl>			<span class=p>|</span>-&gt; PlaneSectionService.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; SectionCreationService.cs
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Utilities
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; Geometry_Utils.cs
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; Ribbon_Utils.cs
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Views
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; AutoSectScenarioWindow.xaml
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; ReferencePlaneSelectionWindow.xaml
</span></span><span class=line><span class=cl>		<span class=p>|</span>-&gt; RevitSectionCreatorWindow.xaml
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Application.cs  
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; Host.cs         
</span></span><span class=line><span class=cl>	<span class=p>|</span>-&gt; UKON.addin
</span></span></code></pre></td></tr></table></div></div><hr><h1 id=cmd_autosectcs><code>Cmd_AutoSect.cs</code><a hidden class=anchor aria-hidden=true href=#cmd_autosectcs>#</a></h1><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span><span class=lnt>11
</span><span class=lnt>12
</span><span class=lnt>13
</span><span class=lnt>14
</span><span class=lnt>15
</span><span class=lnt>16
</span><span class=lnt>17
</span><span class=lnt>18
</span><span class=lnt>19
</span><span class=lnt>20
</span><span class=lnt>21
</span><span class=lnt>22
</span><span class=lnt>23
</span><span class=lnt>24
</span><span class=lnt>25
</span><span class=lnt>26
</span><span class=lnt>27
</span><span class=lnt>28
</span><span class=lnt>29
</span><span class=lnt>30
</span><span class=lnt>31
</span><span class=lnt>32
</span><span class=lnt>33
</span><span class=lnt>34
</span><span class=lnt>35
</span><span class=lnt>36
</span><span class=lnt>37
</span><span class=lnt>38
</span><span class=lnt>39
</span><span class=lnt>40
</span><span class=lnt>41
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-C# data-lang=C#><span class=line><span class=cl><span class=k>using</span> <span class=nn>Autodesk.Revit.Attributes</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>Autodesk.Revit.DB</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>Autodesk.Revit.UI</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>UKON.Views</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>UKON.Models.AutoSection.Common</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>UKON.Commands.AutoSection</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>System</span><span class=p>;</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>namespace</span> <span class=nn>UKON.Commands</span>
</span></span><span class=line><span class=cl><span class=p>{</span>
</span></span><span class=line><span class=cl><span class=na>    [Transaction(TransactionMode.Manual)]</span>
</span></span><span class=line><span class=cl>    <span class=kd>public</span> <span class=k>class</span> <span class=nc>Cmd_AutoSect</span> <span class=p>:</span> <span class=n>IExternalCommand</span>
</span></span><span class=line><span class=cl>    <span class=p>{</span>
</span></span><span class=line><span class=cl>        <span class=kd>public</span> <span class=n>Result</span> <span class=n>Execute</span><span class=p>(</span><span class=n>ExternalCommandData</span> <span class=n>commandData</span><span class=p>,</span> <span class=k>ref</span> <span class=kt>string</span> <span class=n>message</span><span class=p>,</span> <span class=n>ElementSet</span> <span class=n>elements</span><span class=p>)</span>
</span></span><span class=line><span class=cl>        <span class=p>{</span>
</span></span><span class=line><span class=cl>            <span class=k>try</span>
</span></span><span class=line><span class=cl>            <span class=p>{</span>
</span></span><span class=line><span class=cl>                <span class=c1>// Показать диалог выбора типа разреза</span>
</span></span><span class=line><span class=cl>                <span class=kt>var</span> <span class=n>scenarioWindow</span> <span class=p>=</span> <span class=k>new</span> <span class=n>AutoSectScenarioWindow</span><span class=p>();</span>
</span></span><span class=line><span class=cl>                <span class=k>if</span> <span class=p>(</span><span class=n>scenarioWindow</span><span class=p>.</span><span class=n>ShowDialog</span><span class=p>()</span> <span class=p>!=</span> <span class=kc>true</span><span class=p>)</span>
</span></span><span class=line><span class=cl>                    <span class=k>return</span> <span class=n>Result</span><span class=p>.</span><span class=n>Cancelled</span><span class=p>;</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>                <span class=kt>var</span> <span class=n>selectedScenario</span> <span class=p>=</span> <span class=n>scenarioWindow</span><span class=p>.</span><span class=n>SelectedScenario</span><span class=p>;</span>
</span></span><span class=line><span class=cl>                
</span></span><span class=line><span class=cl>                <span class=c1>// Делегировать выполнение соответствующей команде</span>
</span></span><span class=line><span class=cl>                <span class=k>return</span> <span class=n>selectedScenario</span> <span class=k>switch</span>
</span></span><span class=line><span class=cl>                <span class=p>{</span>
</span></span><span class=line><span class=cl>                    <span class=n>AutoSectScenario</span><span class=p>.</span><span class=n>ByBody</span> <span class=p>=&gt;</span> <span class=k>new</span> <span class=n>Cmd_AutoSectByBody</span><span class=p>().</span><span class=n>Execute</span><span class=p>(</span><span class=n>commandData</span><span class=p>,</span> <span class=k>ref</span> <span class=n>message</span><span class=p>,</span> <span class=n>elements</span><span class=p>),</span>
</span></span><span class=line><span class=cl>                    <span class=n>AutoSectScenario</span><span class=p>.</span><span class=n>ByPlane</span> <span class=p>=&gt;</span> <span class=k>new</span> <span class=n>Cmd_AutoSectByPlane</span><span class=p>().</span><span class=n>Execute</span><span class=p>(</span><span class=n>commandData</span><span class=p>,</span> <span class=k>ref</span> <span class=n>message</span><span class=p>,</span> <span class=n>elements</span><span class=p>),</span>
</span></span><span class=line><span class=cl>                    <span class=n>AutoSectScenario</span><span class=p>.</span><span class=n>ByModel</span> <span class=p>=&gt;</span> <span class=k>new</span> <span class=n>Cmd_AutoSectByModel</span><span class=p>().</span><span class=n>Execute</span><span class=p>(</span><span class=n>commandData</span><span class=p>,</span> <span class=k>ref</span> <span class=n>message</span><span class=p>,</span> <span class=n>elements</span><span class=p>),</span>
</span></span><span class=line><span class=cl>                    <span class=n>_</span> <span class=p>=&gt;</span> <span class=n>Result</span><span class=p>.</span><span class=n>Cancelled</span>
</span></span><span class=line><span class=cl>                <span class=p>};</span>
</span></span><span class=line><span class=cl>            <span class=p>}</span>
</span></span><span class=line><span class=cl>            <span class=k>catch</span> <span class=p>(</span><span class=n>Exception</span> <span class=n>ex</span><span class=p>)</span>
</span></span><span class=line><span class=cl>            <span class=p>{</span>
</span></span><span class=line><span class=cl>                <span class=n>message</span> <span class=p>=</span> <span class=n>ex</span><span class=p>.</span><span class=n>Message</span><span class=p>;</span>
</span></span><span class=line><span class=cl>                <span class=k>return</span> <span class=n>Result</span><span class=p>.</span><span class=n>Failed</span><span class=p>;</span>
</span></span><span class=line><span class=cl>            <span class=p>}</span>
</span></span><span class=line><span class=cl>        <span class=p>}</span>
</span></span><span class=line><span class=cl>    <span class=p>}</span>
</span></span><span class=line><span class=cl><span class=p>}</span>
</span></span></code></pre></td></tr></table></div></div><h1 id=cmd_autosectbyplanecs><code>Cmd_AutoSectByPlane.cs</code><a hidden class=anchor aria-hidden=true href=#cmd_autosectbyplanecs>#</a></h1><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre tabindex=0 class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span><span class=lnt>11
</span><span class=lnt>12
</span><span class=lnt>13
</span><span class=lnt>14
</span><span class=lnt>15
</span><span class=lnt>16
</span><span class=lnt>17
</span><span class=lnt>18
</span><span class=lnt>19
</span><span class=lnt>20
</span><span class=lnt>21
</span><span class=lnt>22
</span><span class=lnt>23
</span><span class=lnt>24
</span><span class=lnt>25
</span><span class=lnt>26
</span><span class=lnt>27
</span><span class=lnt>28
</span><span class=lnt>29
</span><span class=lnt>30
</span><span class=lnt>31
</span></code></pre></td><td class=lntd><pre tabindex=0 class=chroma><code class=language-C# data-lang=C#><span class=line><span class=cl><span class=k>using</span> <span class=nn>Autodesk.Revit.Attributes</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>Autodesk.Revit.DB</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>Autodesk.Revit.UI</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>UKON.Services</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>UKON.Services.AutoSection</span><span class=p>;</span>
</span></span><span class=line><span class=cl><span class=k>using</span> <span class=nn>System</span><span class=p>;</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=k>namespace</span> <span class=nn>UKON.Commands.AutoSection</span>
</span></span><span class=line><span class=cl><span class=p>{</span>
</span></span><span class=line><span class=cl><span class=na>    [Transaction(TransactionMode.Manual)]</span>
</span></span><span class=line><span class=cl>    <span class=kd>public</span> <span class=k>class</span> <span class=nc>Cmd_AutoSectByPlane</span> <span class=p>:</span> <span class=n>IExternalCommand</span>
</span></span><span class=line><span class=cl>    <span class=p>{</span>
</span></span><span class=line><span class=cl>        <span class=kd>public</span> <span class=n>Result</span> <span class=n>Execute</span><span class=p>(</span><span class=n>ExternalCommandData</span> <span class=n>commandData</span><span class=p>,</span> <span class=k>ref</span> <span class=kt>string</span> <span class=n>message</span><span class=p>,</span> <span class=n>ElementSet</span> <span class=n>elements</span><span class=p>)</span>
</span></span><span class=line><span class=cl>        <span class=p>{</span>
</span></span><span class=line><span class=cl>            <span class=kt>var</span> <span class=n>uiApp</span> <span class=p>=</span> <span class=n>commandData</span><span class=p>.</span><span class=n>Application</span><span class=p>;</span>
</span></span><span class=line><span class=cl>            <span class=kt>var</span> <span class=n>uiDoc</span> <span class=p>=</span> <span class=n>uiApp</span><span class=p>.</span><span class=n>ActiveUIDocument</span><span class=p>;</span>
</span></span><span class=line><span class=cl>            <span class=kt>var</span> <span class=n>doc</span> <span class=p>=</span> <span class=n>uiDoc</span><span class=p>.</span><span class=n>Document</span><span class=p>;</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>            <span class=k>try</span>
</span></span><span class=line><span class=cl>            <span class=p>{</span>
</span></span><span class=line><span class=cl>                <span class=kt>var</span> <span class=n>planeSectionService</span> <span class=p>=</span> <span class=n>Host</span><span class=p>.</span><span class=n>GetService</span><span class=p>&lt;</span><span class=n>PlaneSectionService</span><span class=p>&gt;();</span>
</span></span><span class=line><span class=cl>                <span class=k>return</span> <span class=n>planeSectionService</span><span class=p>.</span><span class=n>ExecuteByPlane</span><span class=p>(</span><span class=n>uiDoc</span><span class=p>);</span>
</span></span><span class=line><span class=cl>            <span class=p>}</span>
</span></span><span class=line><span class=cl>            <span class=k>catch</span> <span class=p>(</span><span class=n>Exception</span> <span class=n>ex</span><span class=p>)</span>
</span></span><span class=line><span class=cl>            <span class=p>{</span>
</span></span><span class=line><span class=cl>                <span class=n>message</span> <span class=p>=</span> <span class=n>ex</span><span class=p>.</span><span class=n>Message</span><span class=p>;</span>
</span></span><span class=line><span class=cl>                <span class=k>return</span> <span class=n>Result</span><span class=p>.</span><span class=n>Failed</span><span class=p>;</span>
</span></span><span class=line><span class=cl>            <span class=p>}</span>
</span></span><span class=line><span class=cl>        <span class=p>}</span>
</span></span><span class=line><span class=cl>    <span class=p>}</span>
</span></span><span class=line><span class=cl><span class=p>}</span>
</span></span></code></pre></td></tr></table></div></div></div><footer class=post-footer><ul class=post-tags><li><a href=https://blog.aydrafting.com/tags/c%23/>C#</a></li><li><a href=https://blog.aydrafting.com/tags/revit/>Revit</a></li><li><a href=https://blog.aydrafting.com/tags/tutorial/>Tutorial</a></li></ul><nav class=paginav><a class=prev href=https://blog.aydrafting.com/posts/lesson-0/><span class=title>« Prev</span><br><span>C# + Revit API: Lesson 0</span></a></nav></footer></article></main><footer class=footer><span>© 2025 AYDrafting. All rights reserved.</span> ·
<span>Powered by
<a href=https://aydrafting.com/ rel="noopener noreferrer" target=_blank>AYDrafting</a> &
<a href=https://github.com/aydimir95/ rel=noopener target=_blank>GitHub</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg viewBox="0 0 12 6" fill="currentColor"><path d="M12 6H0l6-6z"/></svg>
</a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script><script>document.querySelectorAll("pre > code").forEach(e=>{const n=e.parentNode.parentNode,t=document.createElement("button");t.classList.add("copy-code"),t.innerHTML="copy";function s(){t.innerHTML="copied!",setTimeout(()=>{t.innerHTML="copy"},2e3)}t.addEventListener("click",t=>{if("clipboard"in navigator){navigator.clipboard.writeText(e.textContent),s();return}const n=document.createRange();n.selectNodeContents(e);const o=window.getSelection();o.removeAllRanges(),o.addRange(n);try{document.execCommand("copy"),s()}catch{}o.removeRange(n)}),n.classList.contains("highlight")?n.appendChild(t):n.parentNode.firstChild==n||(e.parentNode.parentNode.parentNode.parentNode.parentNode.nodeName=="TABLE"?e.parentNode.parentNode.parentNode.parentNode.parentNode.appendChild(t):e.parentNode.appendChild(t))})</script></body></html>